/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/bootstrap_probe.am
 * Mode      : Executable
 * Namespace : Amalgame
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Amalgame */
#include "Amalgame_Collections.h"

/* ── Forward Declarations ── */
/* ── Lambda functions (pre-scanned) ── */
static intptr_t _lambda_1(intptr_t x) { return (intptr_t)(x * 2); }

typedef enum { Amalgame_Shape_Circle_TAG, Amalgame_Shape_Rectangle_TAG } Amalgame_Shape_Tag;
typedef struct _Amalgame_Shape Amalgame_Shape;
typedef struct _Amalgame_Stack Amalgame_Stack;
typedef struct _Amalgame_Eval Amalgame_Eval;
static i64 Amalgame_Eval_Area(Amalgame_Shape);
typedef struct _Amalgame_Position Amalgame_Position;
typedef struct _Amalgame_Entity Amalgame_Entity;
typedef struct _Amalgame_Program Amalgame_Program;
static void Amalgame_Program_Main(int, char**);



#line 6 "./tests/samples/bootstrap_probe.am"
/* class Stack */
struct _Amalgame_Stack {
    AmalgameList* Items;
};


#line 9 "./tests/samples/bootstrap_probe.am"
Amalgame_Stack* Amalgame_Stack_new() {
    Amalgame_Stack* self = (Amalgame_Stack*) code_alloc(sizeof(Amalgame_Stack));
{

#line 10 "./tests/samples/bootstrap_probe.am"
        self->Items = AmalgameList_new();
    }    return self;
}


#line 13 "./tests/samples/bootstrap_probe.am"
void Amalgame_Stack_Push(Amalgame_Stack* self, void* item) {

#line 14 "./tests/samples/bootstrap_probe.am"
    AmalgameList_add(self->Items, (void*)(intptr_t)(item));
}


#line 17 "./tests/samples/bootstrap_probe.am"
i64 Amalgame_Stack_Count(Amalgame_Stack* self) {
    return AmalgameList_size(self->Items);
}



#line 21 "./tests/samples/bootstrap_probe.am"
/* enum Shape (tagged union) */
struct _Amalgame_Shape {
    Amalgame_Shape_Tag tag;
    union {
        struct {
            i64 _v0;
        } circle;
        struct {
            i64 _v0;
            i64 _v1;
        } rectangle;
    } data;
}; /* struct _Amalgame_Shape */

static inline Amalgame_Shape Amalgame_Shape_Circle(i64 _v0) {
    Amalgame_Shape _r;
    _r.tag = Amalgame_Shape_Circle_TAG;
    _r.data.circle._v0 = _v0;
    return _r;
}
static inline Amalgame_Shape Amalgame_Shape_Rectangle(i64 _v0, i64 _v1) {
    Amalgame_Shape _r;
    _r.tag = Amalgame_Shape_Rectangle_TAG;
    _r.data.rectangle._v0 = _v0;
    _r.data.rectangle._v1 = _v1;
    return _r;
}



#line 26 "./tests/samples/bootstrap_probe.am"
/* class Eval */
struct _Amalgame_Eval {
};

Amalgame_Eval* Amalgame_Eval_new() {
    Amalgame_Eval* self = (Amalgame_Eval*) code_alloc(sizeof(Amalgame_Eval));
    return self;
}


#line 27 "./tests/samples/bootstrap_probe.am"
static i64 Amalgame_Eval_Area(Amalgame_Shape s) {

#line 28 "./tests/samples/bootstrap_probe.am"
    /* match */
    {
        int _match_idx = 0;
        if (s.tag == Amalgame_Shape_Circle_TAG) {
            intptr_t r = (intptr_t)(s.data.circle._v0);
            return r * r;
        }
        else if (s.tag == Amalgame_Shape_Rectangle_TAG) {
            intptr_t w = (intptr_t)(s.data.rectangle._v0);
            intptr_t h = (intptr_t)(s.data.rectangle._v1);
            return w * h;
        }
    }
}



#line 36 "./tests/samples/bootstrap_probe.am"
/* class Position */
struct _Amalgame_Position {
    i64 X;
    i64 Y;
};


#line 40 "./tests/samples/bootstrap_probe.am"
Amalgame_Position* Amalgame_Position_new(i64 x, i64 y) {
    Amalgame_Position* self = (Amalgame_Position*) code_alloc(sizeof(Amalgame_Position));
{

#line 41 "./tests/samples/bootstrap_probe.am"
        self->X = x;

#line 42 "./tests/samples/bootstrap_probe.am"
        self->Y = y;
    }    return self;
}



#line 46 "./tests/samples/bootstrap_probe.am"
/* class Entity */
struct _Amalgame_Entity {
    Amalgame_Position* Pos;
    code_string Name;
};


#line 50 "./tests/samples/bootstrap_probe.am"
Amalgame_Entity* Amalgame_Entity_new(code_string name, Amalgame_Position* pos) {
    Amalgame_Entity* self = (Amalgame_Entity*) code_alloc(sizeof(Amalgame_Entity));
{

#line 51 "./tests/samples/bootstrap_probe.am"
        self->Name = name;

#line 52 "./tests/samples/bootstrap_probe.am"
        self->Pos = pos;
    }    return self;
}



#line 57 "./tests/samples/bootstrap_probe.am"
/* class Program */
struct _Amalgame_Program {
};

Amalgame_Program* Amalgame_Program_new() {
    Amalgame_Program* self = (Amalgame_Program*) code_alloc(sizeof(Amalgame_Program));
    return self;
}


#line 58 "./tests/samples/bootstrap_probe.am"
static void Amalgame_Program_Main(int argc, char** argv) {

#line 60 "./tests/samples/bootstrap_probe.am"
    Amalgame_Stack* stack = Amalgame_Stack_new();

#line 61 "./tests/samples/bootstrap_probe.am"
    Amalgame_Stack_Push(stack, (void*)(intptr_t)(10));

#line 62 "./tests/samples/bootstrap_probe.am"
    Amalgame_Stack_Push(stack, (void*)(intptr_t)(20));

#line 63 "./tests/samples/bootstrap_probe.am"
    i64 count = Amalgame_Stack_Count(stack);

#line 64 "./tests/samples/bootstrap_probe.am"
    Console_WriteLine(code_string_format("stack count: %s", code_int_to_string(count)));

#line 67 "./tests/samples/bootstrap_probe.am"
    Amalgame_Shape s = Amalgame_Shape_Circle(5);

#line 68 "./tests/samples/bootstrap_probe.am"
    i64 area = Amalgame_Eval_Area(s);

#line 69 "./tests/samples/bootstrap_probe.am"
    Console_WriteLine(code_string_format("area: %s", code_int_to_string(area)));

#line 71 "./tests/samples/bootstrap_probe.am"
    Amalgame_Shape s2 = Amalgame_Shape_Rectangle(4, 6);

#line 72 "./tests/samples/bootstrap_probe.am"
    i64 area2 = Amalgame_Eval_Area(s2);

#line 73 "./tests/samples/bootstrap_probe.am"
    Console_WriteLine(code_string_format("area2: %s", code_int_to_string(area2)));

#line 76 "./tests/samples/bootstrap_probe.am"
    Amalgame_Position* pos = Amalgame_Position_new(42, 10);

#line 77 "./tests/samples/bootstrap_probe.am"
    Amalgame_Entity* ent = Amalgame_Entity_new("Hero", pos);

#line 78 "./tests/samples/bootstrap_probe.am"
    i64 ex = ent->Pos->X;

#line 79 "./tests/samples/bootstrap_probe.am"
    Console_WriteLine(code_string_format("entity x: %s", code_int_to_string(ex)));

#line 82 "./tests/samples/bootstrap_probe.am"
    void* doubler = _lambda_1;

#line 83 "./tests/samples/bootstrap_probe.am"
    i64 d = ((intptr_t(*)(intptr_t))doubler)((intptr_t)(5));

#line 84 "./tests/samples/bootstrap_probe.am"
    Console_WriteLine(code_string_format("doubled: %s", code_int_to_string(d)));

#line 87 "./tests/samples/bootstrap_probe.am"
    i64 total = 0;

#line 88 "./tests/samples/bootstrap_probe.am"
        for (i64 i = 0; i < 3; i++) {
        total = total + i;
    }

#line 91 "./tests/samples/bootstrap_probe.am"
    Console_WriteLine(code_string_format("total: %s", code_int_to_string(total)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Amalgame_Program_Main(argc, argv);
    return 0;
}
