/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/classes.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Animal Tests_Animal;
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main();



#line 3 "./tests/samples/classes.am"
/* class Animal */
struct _Tests_Animal {
    code_string Name;
    i64 Age;
};


#line 7 "./tests/samples/classes.am"
Tests_Animal* Tests_Animal_new(code_string name, i64 age) {
    Tests_Animal* self = (Tests_Animal*) code_alloc(sizeof(Tests_Animal));
{

#line 8 "./tests/samples/classes.am"
        self->Name = name;

#line 9 "./tests/samples/classes.am"
        self->Age = age;
    }    return self;
}


#line 12 "./tests/samples/classes.am"
void Tests_Animal_Speak(Tests_Animal* self) {

#line 13 "./tests/samples/classes.am"
    Console_WriteLine(code_string_format("%s says hello!", self->Name));
}


#line 16 "./tests/samples/classes.am"
code_string Tests_Animal_Describe(Tests_Animal* self) {

#line 17 "./tests/samples/classes.am"
    return code_string_format("%s is %s years old", self->Name, code_int_to_string(self->Age));
}



#line 21 "./tests/samples/classes.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 22 "./tests/samples/classes.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 23 "./tests/samples/classes.am"
    Tests_Animal* cat = Tests_Animal_new("Cat", 3);

#line 24 "./tests/samples/classes.am"
    Tests_Animal* dog = Tests_Animal_new("Dog", 5);

#line 26 "./tests/samples/classes.am"
    Tests_Animal_Speak(cat);

#line 27 "./tests/samples/classes.am"
    Tests_Animal_Speak(dog);

#line 29 "./tests/samples/classes.am"
    code_string desc = Tests_Animal_Describe(cat);

#line 30 "./tests/samples/classes.am"
    Console_WriteLine(desc);
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
