/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/data_classes.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Point Tests_Point;
typedef struct _Tests_Player Tests_Player;
typedef struct _Tests_Program Tests_Program;
static f32 Tests_Program_Distance();
static code_bool Tests_Program_IsAlive();
static void Tests_Program_PrintPlayer();
static void Tests_Program_Main();



#line 3 "./tests/samples/data_classes.am"
/* data class Point */
struct _Tests_Point {
    f32 X;
    f32 Y;
};

Tests_Point* Tests_Point_new(f32 X, f32 Y) {
    Tests_Point* self = (Tests_Point*) code_alloc(sizeof(Tests_Point));
    self->X = X;
    self->Y = Y;
    return self;
}



#line 5 "./tests/samples/data_classes.am"
/* data class Player */
struct _Tests_Player {
    code_string Name;
    i64 Health;
    i64 Level;
};

Tests_Player* Tests_Player_new(code_string Name, i64 Health, i64 Level) {
    Tests_Player* self = (Tests_Player*) code_alloc(sizeof(Tests_Player));
    self->Name = Name;
    self->Health = Health;
    self->Level = Level;
    return self;
}



#line 7 "./tests/samples/data_classes.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 8 "./tests/samples/data_classes.am"
static f32 Tests_Program_Distance(Tests_Point* a, Tests_Point* b) {

#line 9 "./tests/samples/data_classes.am"
    f32 dx = a->X - b->X;

#line 10 "./tests/samples/data_classes.am"
    f32 dy = a->Y - b->Y;

#line 11 "./tests/samples/data_classes.am"
    return dx * dx + dy * dy;
}


#line 14 "./tests/samples/data_classes.am"
static code_bool Tests_Program_IsAlive(Tests_Player* p) {

#line 15 "./tests/samples/data_classes.am"
    return p->Health > 0;
}


#line 18 "./tests/samples/data_classes.am"
static void Tests_Program_PrintPlayer(Tests_Player* p) {

#line 19 "./tests/samples/data_classes.am"
    Console_WriteLine(code_string_format("Player: %s HP=%s Lvl=%s", p->Name, code_int_to_string(p->Health), code_int_to_string(p->Level)));
}


#line 22 "./tests/samples/data_classes.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 23 "./tests/samples/data_classes.am"
    Tests_Point* origin = Tests_Point_new(0.0, 0.0);

#line 24 "./tests/samples/data_classes.am"
    Tests_Point* target = Tests_Point_new(3.0, 4.0);

#line 26 "./tests/samples/data_classes.am"
    f32 dist = Tests_Program_Distance(origin, target);

#line 27 "./tests/samples/data_classes.am"
    Console_WriteLine(code_string_format("Distance squared: %s", code_float_to_string(dist)));

#line 29 "./tests/samples/data_classes.am"
    Tests_Player* hero = Tests_Player_new("Arthus", 100, 42);

#line 30 "./tests/samples/data_classes.am"
    Tests_Player* fallen = Tests_Player_new("Ghost", 0, 10);

#line 32 "./tests/samples/data_classes.am"
    Tests_Program_PrintPlayer(hero);

#line 33 "./tests/samples/data_classes.am"
    Tests_Program_PrintPlayer(fallen);

#line 35 "./tests/samples/data_classes.am"
    code_bool alive = Tests_Program_IsAlive(hero);

#line 36 "./tests/samples/data_classes.am"
    Console_WriteLine(code_string_format("Arthus alive: %s", ((alive) ? "true" : "false")));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
