/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/enums.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef enum { Tests_Direction_North, Tests_Direction_South, Tests_Direction_East, Tests_Direction_West } Tests_Direction;
typedef enum { Tests_Season_Spring, Tests_Season_Summer, Tests_Season_Autumn, Tests_Season_Winter } Tests_Season;
typedef struct _Tests_Program Tests_Program;
static code_string Tests_Program_DirectionName(Tests_Direction*);
static code_bool Tests_Program_IsWarm(Tests_Season*);
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/enums.am"
/* enum Direction — typedef emitted above */



#line 7 "./tests/samples/enums.am"
/* enum Season — typedef emitted above */



#line 11 "./tests/samples/enums.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 12 "./tests/samples/enums.am"
static code_string Tests_Program_DirectionName(Tests_Direction* d) {

#line 13 "./tests/samples/enums.am"
    /* match */
    {
        int _match_idx = 0;
        if (d == Tests_Direction_North) {
            return "North";
        }
        else if (d == Tests_Direction_South) {
            return "South";
        }
        else if (d == Tests_Direction_East) {
            return "East";
        }
        else if (d == Tests_Direction_West) {
            return "West";
        }
        else {
            return "Unknown";
        }
    }

#line 20 "./tests/samples/enums.am"
    return "Unknown";
}


#line 23 "./tests/samples/enums.am"
static code_bool Tests_Program_IsWarm(Tests_Season* s) {

#line 24 "./tests/samples/enums.am"
    /* match */
    {
        int _match_idx = 0;
        if (s == Tests_Season_Spring) {
            return true;
        }
        else if (s == Tests_Season_Summer) {
            return true;
        }
        else {
            return false;
        }
    }

#line 29 "./tests/samples/enums.am"
    return false;
}


#line 32 "./tests/samples/enums.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 33 "./tests/samples/enums.am"
    void* d = Tests_Direction_North;

#line 34 "./tests/samples/enums.am"
    code_string name = Tests_Program_DirectionName(d);

#line 35 "./tests/samples/enums.am"
    Console_WriteLine(code_string_format("Direction: %s", name));

#line 37 "./tests/samples/enums.am"
    void* s1 = Tests_Season_Summer;

#line 38 "./tests/samples/enums.am"
    void* s2 = Tests_Season_Winter;

#line 39 "./tests/samples/enums.am"
    code_bool w1 = Tests_Program_IsWarm(s1);

#line 40 "./tests/samples/enums.am"
    code_bool w2 = Tests_Program_IsWarm(s2);

#line 41 "./tests/samples/enums.am"
    Console_WriteLine(code_string_format("Summer warm: %s", ((w1) ? "true" : "false")));

#line 42 "./tests/samples/enums.am"
    Console_WriteLine(code_string_format("Winter warm: %s", ((w2) ? "true" : "false")));

#line 45 "./tests/samples/enums.am"
    code_bool isNorth = d == Tests_Direction_North;

#line 46 "./tests/samples/enums.am"
    Console_WriteLine(code_string_format("isNorth: %s", ((isNorth) ? "true" : "false")));

#line 49 "./tests/samples/enums.am"
    code_string s = Tests_Program_DirectionName(Tests_Direction_East);

#line 50 "./tests/samples/enums.am"
    Console_WriteLine(code_string_format("East: %s", s));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
