/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/forced_lib.am
 * Mode      : Executable
 * Namespace : MyApp
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace MyApp */

/* ── Forward Declarations ── */
typedef struct _MyApp_Config MyApp_Config;
typedef struct _MyApp_Program MyApp_Program;
static void MyApp_Program_Main(int, char**);



#line 3 "./tests/samples/forced_lib.am"
/* class Config */
struct _MyApp_Config {
    code_string Host;
    i64 Port;
};


#line 7 "./tests/samples/forced_lib.am"
MyApp_Config* MyApp_Config_new(code_string host, i64 port) {
    MyApp_Config* self = (MyApp_Config*) code_alloc(sizeof(MyApp_Config));
{

#line 8 "./tests/samples/forced_lib.am"
        self->Host = host;

#line 9 "./tests/samples/forced_lib.am"
        self->Port = port;
    }    return self;
}


#line 12 "./tests/samples/forced_lib.am"
code_string MyApp_Config_Address(MyApp_Config* self) {

#line 13 "./tests/samples/forced_lib.am"
    return code_string_format("%s:%s", self->Host, code_int_to_string(self->Port));
}



#line 17 "./tests/samples/forced_lib.am"
/* class Program */
struct _MyApp_Program {
};

MyApp_Program* MyApp_Program_new() {
    MyApp_Program* self = (MyApp_Program*) code_alloc(sizeof(MyApp_Program));
    return self;
}


#line 18 "./tests/samples/forced_lib.am"
static void MyApp_Program_Main(int argc, char** argv) {

#line 19 "./tests/samples/forced_lib.am"
    MyApp_Config* cfg = MyApp_Config_new("localhost", 8080);

#line 20 "./tests/samples/forced_lib.am"
    Console_WriteLine(MyApp_Config_Address(cfg));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    MyApp_Program_Main(argc, argv);
    return 0;
}
