/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/foreach.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */
#include "Amalgame_Collections.h"

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 5 "./tests/samples/foreach.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 6 "./tests/samples/foreach.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 8 "./tests/samples/foreach.am"
    i64 sum = 0;

#line 9 "./tests/samples/foreach.am"
        for (i64 i = 0; i < 5; i++) {
        sum = sum + i;
    }

#line 12 "./tests/samples/foreach.am"
    Console_WriteLine(code_string_format("sum 0..5: %s", code_int_to_string(sum)));

#line 15 "./tests/samples/foreach.am"
    AmalgameList* list = AmalgameList_new();

#line 16 "./tests/samples/foreach.am"
    AmalgameList_add(list, (void*)(intptr_t)(10));

#line 17 "./tests/samples/foreach.am"
    AmalgameList_add(list, (void*)(intptr_t)(20));

#line 18 "./tests/samples/foreach.am"
    AmalgameList_add(list, (void*)(intptr_t)(30));

#line 20 "./tests/samples/foreach.am"
    i64 total = 0;

#line 21 "./tests/samples/foreach.am"
        {
        AmalgameList* _lst = (AmalgameList*)(list);
        for (int _i = 0; _i < _lst->size; _i++) {
            void* item = AmalgameList_get(_lst, _i);
            total = total + 1;
        }
    }

#line 24 "./tests/samples/foreach.am"
    Console_WriteLine(code_string_format("list total: %s", code_int_to_string(total)));

#line 27 "./tests/samples/foreach.am"
        {
        AmalgameList* _lst = (AmalgameList*)(list);
        for (i64 i = 0; i < _lst->size; i++) {
            void* item = AmalgameList_get(_lst, i);
            Console_WriteLine(code_string_format("item[%s] = %s", code_int_to_string(i), code_int_to_string(i)));
        }
    }

#line 32 "./tests/samples/foreach.am"
    i64 count = 0;

#line 33 "./tests/samples/foreach.am"
        {
        code_string _str = (code_string)("Hello");
        i64 _slen = (i64) strlen(_str);
        for (i64 _i = 0; _i < _slen; _i++) {
            char ch = _str[_i];
            count = count + 1;
        }
    }

#line 36 "./tests/samples/foreach.am"
    Console_WriteLine(code_string_format("chars: %s", code_int_to_string(count)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
