/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/generics.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Stack Tests_Stack;
static void Tests_Stack_Push(Tests_Stack*, i64);
static i64 Tests_Stack_Size(Tests_Stack*);
typedef struct _Tests_Pair Tests_Pair;
static code_string Tests_Pair_ToString(Tests_Pair*);
typedef struct _Tests_Program Tests_Program;
static i64 Tests_Program_Max(i64, i64);
static code_string Tests_Program_Repeat(code_string, i64);
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/generics.am"
/* class Stack */
struct _Tests_Stack {
    i64* Items;
    i64 Size;
};


#line 7 "./tests/samples/generics.am"
Tests_Stack* Tests_Stack_new() {
    Tests_Stack* self = (Tests_Stack*) code_alloc(sizeof(Tests_Stack));
{

#line 8 "./tests/samples/generics.am"
        self->Size = 0;
    }    return self;
}


#line 11 "./tests/samples/generics.am"
void Tests_Stack_Push(Tests_Stack* self, i64 value) {

#line 12 "./tests/samples/generics.am"
    self->Size = self->Size + 1;

#line 13 "./tests/samples/generics.am"
    Console_WriteLine(code_string_format("Pushed: %s", code_int_to_string(value)));
}


#line 16 "./tests/samples/generics.am"
i64 Tests_Stack_Size(Tests_Stack* self) {

#line 17 "./tests/samples/generics.am"
    return self->Size;
}



#line 21 "./tests/samples/generics.am"
/* class Pair */
struct _Tests_Pair {
    code_string First;
    i64 Second;
};


#line 25 "./tests/samples/generics.am"
Tests_Pair* Tests_Pair_new(code_string first, i64 second) {
    Tests_Pair* self = (Tests_Pair*) code_alloc(sizeof(Tests_Pair));
{

#line 26 "./tests/samples/generics.am"
        self->First = first;

#line 27 "./tests/samples/generics.am"
        self->Second = second;
    }    return self;
}


#line 30 "./tests/samples/generics.am"
code_string Tests_Pair_ToString(Tests_Pair* self) {

#line 31 "./tests/samples/generics.am"
    return code_string_format("(%s, %s)", self->First, code_int_to_string(self->Second));
}



#line 35 "./tests/samples/generics.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 36 "./tests/samples/generics.am"
static i64 Tests_Program_Max(i64 a, i64 b) {

#line 37 "./tests/samples/generics.am"
    if (a > b) {

#line 38 "./tests/samples/generics.am"
        return a;
    }

#line 40 "./tests/samples/generics.am"
    return b;
}


#line 43 "./tests/samples/generics.am"
static code_string Tests_Program_Repeat(code_string s, i64 n) {

#line 44 "./tests/samples/generics.am"
    code_string result = "";

#line 45 "./tests/samples/generics.am"
    i64 i = 0;

#line 46 "./tests/samples/generics.am"
    while (i < n) {

#line 47 "./tests/samples/generics.am"
        result = code_string_concat(result, s);

#line 48 "./tests/samples/generics.am"
        i = i + 1;
    }

#line 50 "./tests/samples/generics.am"
    return result;
}


#line 53 "./tests/samples/generics.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 54 "./tests/samples/generics.am"
    Tests_Pair* p1 = Tests_Pair_new("hello", 42);

#line 55 "./tests/samples/generics.am"
    Tests_Pair* p2 = Tests_Pair_new("world", 99);

#line 57 "./tests/samples/generics.am"
    Console_WriteLine(Tests_Pair_ToString(p1));

#line 58 "./tests/samples/generics.am"
    Console_WriteLine(Tests_Pair_ToString(p2));

#line 60 "./tests/samples/generics.am"
    i64 bigger = Tests_Program_Max(p1->Second, p2->Second);

#line 61 "./tests/samples/generics.am"
    Console_WriteLine(code_string_format("Max: %s", code_int_to_string(bigger)));

#line 63 "./tests/samples/generics.am"
    code_string rep = Tests_Program_Repeat("ab", 3);

#line 64 "./tests/samples/generics.am"
    Console_WriteLine(code_string_format("Repeat: %s", rep));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
