/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/hello.am
 * Mode      : Executable
 * Namespace : MyApp
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace MyApp */
/* import Code.IO */

/* ── Forward Declarations ── */
typedef struct _MyApp_Program MyApp_Program;
static void MyApp_Program_Main(int, char**);



#line 5 "./tests/samples/hello.am"
/* class Program */
struct _MyApp_Program {
};

MyApp_Program* MyApp_Program_new() {
    MyApp_Program* self = (MyApp_Program*) code_alloc(sizeof(MyApp_Program));
    return self;
}


#line 6 "./tests/samples/hello.am"
static void MyApp_Program_Main(int argc, char** argv) {

#line 7 "./tests/samples/hello.am"
    code_string name = "World";

#line 8 "./tests/samples/hello.am"
    Console_WriteLine(code_string_format("Hello %s !", name));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    MyApp_Program_Main(argc, argv);
    return 0;
}
