/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/if_expr.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/if_expr.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/if_expr.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 5 "./tests/samples/if_expr.am"
    i64 x = 10;

#line 8 "./tests/samples/if_expr.am"
    code_string label = ((x > 5) ? ("big") : ("small"));

#line 9 "./tests/samples/if_expr.am"
    Console_WriteLine(code_string_format("label: %s", label));

#line 12 "./tests/samples/if_expr.am"
    i64 score = 75;

#line 13 "./tests/samples/if_expr.am"
    code_string grade = ((score >= 90) ? ("A") : (score >= 80) ? ("B") : (score >= 70) ? ("C") : ("F"));

#line 14 "./tests/samples/if_expr.am"
    Console_WriteLine(code_string_format("grade: %s", grade));

#line 17 "./tests/samples/if_expr.am"
    i64 bigger = ((x > 3) ? (x) : (3));

#line 18 "./tests/samples/if_expr.am"
    Console_WriteLine(code_string_format("bigger: %s", code_int_to_string(bigger)));

#line 21 "./tests/samples/if_expr.am"
    code_bool isAdult = ((x >= 18) ? (true) : (false));

#line 22 "./tests/samples/if_expr.am"
    Console_WriteLine(code_string_format("adult: %s", ((isAdult) ? "true" : "false")));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
