/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/inheritance.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Shape Tests_Shape;
static code_string Tests_Shape_Describe(Tests_Shape*);
typedef struct _Tests_Circle Tests_Circle;
static f32 Tests_Circle_Area(Tests_Circle*);
static code_string Tests_Circle_Describe(Tests_Circle*);
typedef struct _Tests_Rectangle Tests_Rectangle;
static f32 Tests_Rectangle_Area(Tests_Rectangle*);
static code_string Tests_Rectangle_Describe(Tests_Rectangle*);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/inheritance.am"
/* class Shape */
struct _Tests_Shape {
    code_string Name;
};


#line 6 "./tests/samples/inheritance.am"
Tests_Shape* Tests_Shape_new(code_string name) {
    Tests_Shape* self = (Tests_Shape*) code_alloc(sizeof(Tests_Shape));
{

#line 7 "./tests/samples/inheritance.am"
        self->Name = name;
    }    return self;
}


#line 10 "./tests/samples/inheritance.am"
code_string Tests_Shape_Describe(Tests_Shape* self) {

#line 11 "./tests/samples/inheritance.am"
    return code_string_format("Shape: %s", self->Name);
}



#line 15 "./tests/samples/inheritance.am"
/* class Circle */
struct _Tests_Circle {
    struct _Tests_Shape _base; /* extends Tests_Shape */
    f32 Radius;
};


#line 18 "./tests/samples/inheritance.am"
Tests_Circle* Tests_Circle_new(code_string name, f32 radius) {
    Tests_Circle* self = (Tests_Circle*) code_alloc(sizeof(Tests_Circle));
{

#line 19 "./tests/samples/inheritance.am"
        self->_base.Name = name;

#line 20 "./tests/samples/inheritance.am"
        self->Radius = radius;
    }    return self;
}


#line 23 "./tests/samples/inheritance.am"
f32 Tests_Circle_Area(Tests_Circle* self) {

#line 24 "./tests/samples/inheritance.am"
    return 3.14159 * self->Radius * self->Radius;
}


#line 27 "./tests/samples/inheritance.am"
code_string Tests_Circle_Describe(Tests_Circle* self) {

#line 28 "./tests/samples/inheritance.am"
    return code_string_format("Circle '%s' r=%s", self->_base.Name, code_float_to_string(self->Radius));
}



#line 32 "./tests/samples/inheritance.am"
/* class Rectangle */
struct _Tests_Rectangle {
    struct _Tests_Shape _base; /* extends Tests_Shape */
    f32 Width;
    f32 Height;
};


#line 36 "./tests/samples/inheritance.am"
Tests_Rectangle* Tests_Rectangle_new(code_string name, f32 width, f32 height) {
    Tests_Rectangle* self = (Tests_Rectangle*) code_alloc(sizeof(Tests_Rectangle));
{

#line 37 "./tests/samples/inheritance.am"
        self->_base.Name = name;

#line 38 "./tests/samples/inheritance.am"
        self->Width = width;

#line 39 "./tests/samples/inheritance.am"
        self->Height = height;
    }    return self;
}


#line 42 "./tests/samples/inheritance.am"
f32 Tests_Rectangle_Area(Tests_Rectangle* self) {

#line 43 "./tests/samples/inheritance.am"
    return self->Width * self->Height;
}


#line 46 "./tests/samples/inheritance.am"
code_string Tests_Rectangle_Describe(Tests_Rectangle* self) {

#line 47 "./tests/samples/inheritance.am"
    return code_string_format("Rectangle '%s' %sx%s", self->_base.Name, code_float_to_string(self->Width), code_float_to_string(self->Height));
}



#line 51 "./tests/samples/inheritance.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 52 "./tests/samples/inheritance.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 53 "./tests/samples/inheritance.am"
    Tests_Circle* c = Tests_Circle_new("Sun", 5.0);

#line 54 "./tests/samples/inheritance.am"
    Tests_Rectangle* r = Tests_Rectangle_new("Wall", 4.0, 6.0);

#line 56 "./tests/samples/inheritance.am"
    Console_WriteLine(Tests_Circle_Describe(c));

#line 57 "./tests/samples/inheritance.am"
    Console_WriteLine(Tests_Rectangle_Describe(r));

#line 59 "./tests/samples/inheritance.am"
    f32 ca = Tests_Circle_Area(c);

#line 60 "./tests/samples/inheritance.am"
    f32 ra = Tests_Rectangle_Area(r);

#line 62 "./tests/samples/inheritance.am"
    Console_WriteLine(code_string_format("Circle area: %s", code_float_to_string(ca)));

#line 63 "./tests/samples/inheritance.am"
    Console_WriteLine(code_string_format("Rectangle area: %s", code_float_to_string(ra)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
