/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/interfaces.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_IDescribable_vtable Tests_IDescribable_vtable;
typedef struct _Tests_IDescribable Tests_IDescribable;
typedef struct _Tests_IScalable_vtable Tests_IScalable_vtable;
typedef struct _Tests_IScalable Tests_IScalable;
typedef struct _Tests_Circle Tests_Circle;
static code_string Tests_Circle_Describe(Tests_Circle*);
static void Tests_Circle_Scale(Tests_Circle*, f32);
typedef struct _Tests_Rectangle Tests_Rectangle;
static code_string Tests_Rectangle_Describe(Tests_Rectangle*);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_PrintDesc(Tests_IDescribable);
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/interfaces.am"
/* interface IDescribable */
typedef struct _Tests_IDescribable_vtable {
    code_string (*Describe)(void*);
} Tests_IDescribable_vtable;

typedef struct _Tests_IDescribable {
    Tests_IDescribable_vtable* vtable;
    void*           self;
} Tests_IDescribable;



#line 7 "./tests/samples/interfaces.am"
/* interface IScalable */
typedef struct _Tests_IScalable_vtable {
    void (*Scale)(void*, f32);
} Tests_IScalable_vtable;

typedef struct _Tests_IScalable {
    Tests_IScalable_vtable* vtable;
    void*           self;
} Tests_IScalable;



#line 11 "./tests/samples/interfaces.am"
/* class Circle */
struct _Tests_Circle {
    f32 Radius;
};


#line 14 "./tests/samples/interfaces.am"
Tests_Circle* Tests_Circle_new(f32 radius) {
    Tests_Circle* self = (Tests_Circle*) code_alloc(sizeof(Tests_Circle));
{

#line 15 "./tests/samples/interfaces.am"
        self->Radius = radius;
    }    return self;
}


#line 18 "./tests/samples/interfaces.am"
code_string Tests_Circle_Describe(Tests_Circle* self) {

#line 19 "./tests/samples/interfaces.am"
    return code_string_format("Circle(r=%s)", code_float_to_string(self->Radius));
}


#line 22 "./tests/samples/interfaces.am"
void Tests_Circle_Scale(Tests_Circle* self, f32 factor) {

#line 23 "./tests/samples/interfaces.am"
    self->Radius = self->Radius * factor;
}

static Tests_IDescribable_vtable Tests_Circle_IDescribable_vtable = {
    .Describe = (void*)Tests_Circle_Describe,
};

static inline Tests_IDescribable Tests_Circle_as_IDescribable(Tests_Circle* self) {
    Tests_IDescribable _r;
    _r.vtable = &Tests_Circle_IDescribable_vtable;
    _r.self   = (void*) self;
    return _r;
}

static Tests_IScalable_vtable Tests_Circle_IScalable_vtable = {
    .Scale = (void*)Tests_Circle_Scale,
};

static inline Tests_IScalable Tests_Circle_as_IScalable(Tests_Circle* self) {
    Tests_IScalable _r;
    _r.vtable = &Tests_Circle_IScalable_vtable;
    _r.self   = (void*) self;
    return _r;
}



#line 27 "./tests/samples/interfaces.am"
/* class Rectangle */
struct _Tests_Rectangle {
    f32 Width;
    f32 Height;
};


#line 31 "./tests/samples/interfaces.am"
Tests_Rectangle* Tests_Rectangle_new(f32 w, f32 h) {
    Tests_Rectangle* self = (Tests_Rectangle*) code_alloc(sizeof(Tests_Rectangle));
{

#line 32 "./tests/samples/interfaces.am"
        self->Width = w;

#line 33 "./tests/samples/interfaces.am"
        self->Height = h;
    }    return self;
}


#line 36 "./tests/samples/interfaces.am"
code_string Tests_Rectangle_Describe(Tests_Rectangle* self) {

#line 37 "./tests/samples/interfaces.am"
    return code_string_format("Rect(%sx%s)", code_float_to_string(self->Width), code_float_to_string(self->Height));
}

static Tests_IDescribable_vtable Tests_Rectangle_IDescribable_vtable = {
    .Describe = (void*)Tests_Rectangle_Describe,
};

static inline Tests_IDescribable Tests_Rectangle_as_IDescribable(Tests_Rectangle* self) {
    Tests_IDescribable _r;
    _r.vtable = &Tests_Rectangle_IDescribable_vtable;
    _r.self   = (void*) self;
    return _r;
}



#line 41 "./tests/samples/interfaces.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 42 "./tests/samples/interfaces.am"
static void Tests_Program_PrintDesc(Tests_IDescribable obj) {

#line 43 "./tests/samples/interfaces.am"
    void* d = obj.vtable->Describe(obj.self);

#line 44 "./tests/samples/interfaces.am"
    Console_WriteLine(d);
}


#line 47 "./tests/samples/interfaces.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 48 "./tests/samples/interfaces.am"
    Tests_Circle* c = Tests_Circle_new(5.0);

#line 49 "./tests/samples/interfaces.am"
    Tests_Rectangle* r = Tests_Rectangle_new(4.0, 3.0);

#line 52 "./tests/samples/interfaces.am"
    code_string cd = Tests_Circle_Describe(c);

#line 53 "./tests/samples/interfaces.am"
    code_string rd = Tests_Rectangle_Describe(r);

#line 54 "./tests/samples/interfaces.am"
    Console_WriteLine(cd);

#line 55 "./tests/samples/interfaces.am"
    Console_WriteLine(rd);

#line 58 "./tests/samples/interfaces.am"
    Tests_Circle_Scale(c, 2.0);

#line 59 "./tests/samples/interfaces.am"
    code_string cd2 = Tests_Circle_Describe(c);

#line 60 "./tests/samples/interfaces.am"
    Console_WriteLine(cd2);

#line 63 "./tests/samples/interfaces.am"
    Tests_Program_PrintDesc(Tests_Circle_as_IDescribable(c));

#line 64 "./tests/samples/interfaces.am"
    Tests_Program_PrintDesc(Tests_Rectangle_as_IDescribable(r));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
