/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/library.am
 * Mode      : Library
 * Namespace : Amalgame.Utils
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Amalgame.Utils */

/* ── Forward Declarations ── */
typedef struct _Amalgame_Utils_StringHelper Amalgame_Utils_StringHelper;
static code_string Amalgame_Utils_StringHelper_Repeat(code_string, i64);
static i64 Amalgame_Utils_StringHelper_CountChars(code_string, code_string);
typedef struct _Amalgame_Utils_MathHelper Amalgame_Utils_MathHelper;
static i64 Amalgame_Utils_MathHelper_Clamp(i64, i64, i64);
static i64 Amalgame_Utils_MathHelper_Abs(i64);



#line 3 "./tests/samples/library.am"
/* class StringHelper */
struct _Amalgame_Utils_StringHelper {
};

Amalgame_Utils_StringHelper* Amalgame_Utils_StringHelper_new() {
    Amalgame_Utils_StringHelper* self = (Amalgame_Utils_StringHelper*) code_alloc(sizeof(Amalgame_Utils_StringHelper));
    return self;
}


#line 4 "./tests/samples/library.am"
static code_string Amalgame_Utils_StringHelper_Repeat(code_string s, i64 n) {

#line 5 "./tests/samples/library.am"
    code_string result = "";

#line 6 "./tests/samples/library.am"
    i64 i = 0;

#line 7 "./tests/samples/library.am"
    while (i < n) {

#line 8 "./tests/samples/library.am"
        result = code_string_concat(result, s);

#line 9 "./tests/samples/library.am"
        i = i + 1;
    }

#line 11 "./tests/samples/library.am"
    return result;
}


#line 14 "./tests/samples/library.am"
static i64 Amalgame_Utils_StringHelper_CountChars(code_string s, code_string target) {

#line 15 "./tests/samples/library.am"
    return 0;
}



#line 19 "./tests/samples/library.am"
/* class MathHelper */
struct _Amalgame_Utils_MathHelper {
};

Amalgame_Utils_MathHelper* Amalgame_Utils_MathHelper_new() {
    Amalgame_Utils_MathHelper* self = (Amalgame_Utils_MathHelper*) code_alloc(sizeof(Amalgame_Utils_MathHelper));
    return self;
}


#line 20 "./tests/samples/library.am"
static i64 Amalgame_Utils_MathHelper_Clamp(i64 value, i64 min, i64 max) {

#line 21 "./tests/samples/library.am"
    if (value < min) {
        return min;
    }

#line 22 "./tests/samples/library.am"
    if (value > max) {
        return max;
    }

#line 23 "./tests/samples/library.am"
    return value;
}


#line 26 "./tests/samples/library.am"
static i64 Amalgame_Utils_MathHelper_Abs(i64 value) {

#line 27 "./tests/samples/library.am"
    if (value < 0) {
        return 0 - value;
    }

#line 28 "./tests/samples/library.am"
    return value;
}



/* Library — no entry point */
