/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/loops.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/loops.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/loops.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 6 "./tests/samples/loops.am"
    i64 i = 0;

#line 7 "./tests/samples/loops.am"
    while (i < 100) {

#line 8 "./tests/samples/loops.am"
        if (i == 3) {
            break;
        }

#line 9 "./tests/samples/loops.am"
        Console_WriteLine(code_string_format("w: %s", code_int_to_string(i)));

#line 10 "./tests/samples/loops.am"
        i = i + 1;
    }

#line 14 "./tests/samples/loops.am"
    for (i64 j = 0; j < 6; j = j + 1) {

#line 15 "./tests/samples/loops.am"
        if (j % 2 == 0) {
            continue;
        }

#line 16 "./tests/samples/loops.am"
        Console_WriteLine(code_string_format("odd: %s", code_int_to_string(j)));
    }

#line 20 "./tests/samples/loops.am"
    for (i64 r = 0; r < 3; r = r + 1) {

#line 21 "./tests/samples/loops.am"
        for (i64 c = 0; c < 3; c = c + 1) {

#line 22 "./tests/samples/loops.am"
            if (r == c) {

#line 23 "./tests/samples/loops.am"
                Console_WriteLine(code_string_format("diag: %s", code_int_to_string(r)));
            }
        }
    }

#line 29 "./tests/samples/loops.am"
    i64 a = 0;

#line 30 "./tests/samples/loops.am"
    i64 b = 10;

#line 31 "./tests/samples/loops.am"
    while (a < 5 && b > 5) {

#line 32 "./tests/samples/loops.am"
        a = a + 1;

#line 33 "./tests/samples/loops.am"
        b = b - 1;
    }

#line 35 "./tests/samples/loops.am"
    Console_WriteLine(code_string_format("a: %s b: %s", code_int_to_string(a), code_int_to_string(b)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
