/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/math.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_MathHelper Tests_MathHelper;
static i64 Tests_MathHelper_Add(i64, i64);
static i64 Tests_MathHelper_Max(i64, i64);
static i64 Tests_MathHelper_Factorial(i64);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/math.am"
/* class MathHelper */
struct _Tests_MathHelper {
};

Tests_MathHelper* Tests_MathHelper_new() {
    Tests_MathHelper* self = (Tests_MathHelper*) code_alloc(sizeof(Tests_MathHelper));
    return self;
}


#line 4 "./tests/samples/math.am"
static i64 Tests_MathHelper_Add(i64 a, i64 b) {

#line 5 "./tests/samples/math.am"
    return a + b;
}


#line 8 "./tests/samples/math.am"
static i64 Tests_MathHelper_Max(i64 a, i64 b) {

#line 9 "./tests/samples/math.am"
    if (a > b) {

#line 10 "./tests/samples/math.am"
        return a;
    } else {

#line 12 "./tests/samples/math.am"
        return b;
    }
}


#line 16 "./tests/samples/math.am"
static i64 Tests_MathHelper_Factorial(i64 n) {

#line 17 "./tests/samples/math.am"
    if (n <= 1) {

#line 18 "./tests/samples/math.am"
        return 1;
    }

#line 20 "./tests/samples/math.am"
    return n * Tests_MathHelper_Factorial(n - 1);
}



#line 24 "./tests/samples/math.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 25 "./tests/samples/math.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 26 "./tests/samples/math.am"
    i64 sum = Tests_MathHelper_Add(21, 21);

#line 27 "./tests/samples/math.am"
    Console_WriteLine(code_string_format("21 + 21 = %s", code_int_to_string(sum)));

#line 29 "./tests/samples/math.am"
    i64 biggest = Tests_MathHelper_Max(42, 17);

#line 30 "./tests/samples/math.am"
    Console_WriteLine(code_string_format("max(42, 17) = %s", code_int_to_string(biggest)));

#line 32 "./tests/samples/math.am"
    i64 fact = Tests_MathHelper_Factorial(5);

#line 33 "./tests/samples/math.am"
    Console_WriteLine(code_string_format("5! = %s", code_int_to_string(fact)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
