/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/multiline_string.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/multiline_string.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/multiline_string.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 6 "./tests/samples/multiline_string.am"
    code_string msg = "Hello\nWorld";

#line 10 "./tests/samples/multiline_string.am"
    Console_WriteLine("lines: 2");

#line 13 "./tests/samples/multiline_string.am"
    code_string name = "Arthus";

#line 14 "./tests/samples/multiline_string.am"
    i64 level = 42;

#line 15 "./tests/samples/multiline_string.am"
    code_string card = code_string_format("Player: %s\nLevel:  %s", name, code_int_to_string(level));

#line 19 "./tests/samples/multiline_string.am"
    Console_WriteLine(code_string_format("card ok: %s", name));

#line 22 "./tests/samples/multiline_string.am"
    code_string sql = "SELECT *\nFROM players\nWHERE level > 10\n";

#line 27 "./tests/samples/multiline_string.am"
    Console_WriteLine("sql ok");

#line 30 "./tests/samples/multiline_string.am"
    code_string q = "Hello World";

#line 31 "./tests/samples/multiline_string.am"
    Console_WriteLine(code_string_format("single: %s", q));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
