/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/multi_class.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Address Tests_Address;
static code_string Tests_Address_Format(Tests_Address*);
typedef struct _Tests_Person Tests_Person;
static code_string Tests_Person_Describe(Tests_Person*);
static code_bool Tests_Person_IsAdult(Tests_Person*);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/multi_class.am"
/* class Address */
struct _Tests_Address {
    code_string Street;
    code_string City;
    code_string Zip;
};


#line 8 "./tests/samples/multi_class.am"
Tests_Address* Tests_Address_new(code_string street, code_string city, code_string zip) {
    Tests_Address* self = (Tests_Address*) code_alloc(sizeof(Tests_Address));
{

#line 9 "./tests/samples/multi_class.am"
        self->Street = street;

#line 10 "./tests/samples/multi_class.am"
        self->City = city;

#line 11 "./tests/samples/multi_class.am"
        self->Zip = zip;
    }    return self;
}


#line 14 "./tests/samples/multi_class.am"
code_string Tests_Address_Format(Tests_Address* self) {

#line 15 "./tests/samples/multi_class.am"
    return code_string_format("%s, %s %s", self->Street, self->City, self->Zip);
}



#line 19 "./tests/samples/multi_class.am"
/* class Person */
struct _Tests_Person {
    code_string Name;
    i64 Age;
    Tests_Address* Home;
};


#line 24 "./tests/samples/multi_class.am"
Tests_Person* Tests_Person_new(code_string name, i64 age, Tests_Address* home) {
    Tests_Person* self = (Tests_Person*) code_alloc(sizeof(Tests_Person));
{

#line 25 "./tests/samples/multi_class.am"
        self->Name = name;

#line 26 "./tests/samples/multi_class.am"
        self->Age = age;

#line 27 "./tests/samples/multi_class.am"
        self->Home = home;
    }    return self;
}


#line 30 "./tests/samples/multi_class.am"
code_string Tests_Person_Describe(Tests_Person* self) {

#line 31 "./tests/samples/multi_class.am"
    void* fmt = Tests_Address_Format(self->Home);

#line 32 "./tests/samples/multi_class.am"
    return code_string_format("%s (%s) lives at %s", self->Name, code_int_to_string(self->Age), fmt);
}


#line 35 "./tests/samples/multi_class.am"
code_bool Tests_Person_IsAdult(Tests_Person* self) {

#line 36 "./tests/samples/multi_class.am"
    return self->Age >= 18;
}



#line 40 "./tests/samples/multi_class.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 41 "./tests/samples/multi_class.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 42 "./tests/samples/multi_class.am"
    Tests_Address* addr = Tests_Address_new("42 Rue de la Paix", "Paris", "75001");

#line 43 "./tests/samples/multi_class.am"
    Tests_Person* person = Tests_Person_new("Arthus", 28, addr);

#line 45 "./tests/samples/multi_class.am"
    code_string desc = Tests_Person_Describe(person);

#line 46 "./tests/samples/multi_class.am"
    Console_WriteLine(desc);

#line 48 "./tests/samples/multi_class.am"
    code_bool adult = Tests_Person_IsAdult(person);

#line 49 "./tests/samples/multi_class.am"
    Console_WriteLine(code_string_format("Adult: %s", ((adult) ? "true" : "false")));

#line 51 "./tests/samples/multi_class.am"
    code_string city = addr->City;

#line 52 "./tests/samples/multi_class.am"
    Console_WriteLine(code_string_format("City: %s", city));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
