/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/namespace.am
 * Mode      : Executable
 * Namespace : MyApp.Models
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace MyApp.Models */

/* ── Forward Declarations ── */
typedef struct _MyApp_Models_Player MyApp_Models_Player;
static code_string MyApp_Models_Player_Info(MyApp_Models_Player*);
typedef struct _MyApp_Models_Guild MyApp_Models_Guild;
static code_string MyApp_Models_Guild_Describe(MyApp_Models_Guild*);
typedef struct _MyApp_Models_Program MyApp_Models_Program;
static void MyApp_Models_Program_Main(int, char**);



#line 3 "./tests/samples/namespace.am"
/* class Player */
struct _MyApp_Models_Player {
    code_string Name;
    i64 Level;
};


#line 7 "./tests/samples/namespace.am"
MyApp_Models_Player* MyApp_Models_Player_new(code_string name, i64 level) {
    MyApp_Models_Player* self = (MyApp_Models_Player*) code_alloc(sizeof(MyApp_Models_Player));
{

#line 8 "./tests/samples/namespace.am"
        self->Name = name;

#line 9 "./tests/samples/namespace.am"
        self->Level = level;
    }    return self;
}


#line 12 "./tests/samples/namespace.am"
code_string MyApp_Models_Player_Info(MyApp_Models_Player* self) {

#line 13 "./tests/samples/namespace.am"
    return code_string_format("%s (lvl %s)", self->Name, code_int_to_string(self->Level));
}



#line 17 "./tests/samples/namespace.am"
/* class Guild */
struct _MyApp_Models_Guild {
    code_string Tag;
};


#line 20 "./tests/samples/namespace.am"
MyApp_Models_Guild* MyApp_Models_Guild_new(code_string tag) {
    MyApp_Models_Guild* self = (MyApp_Models_Guild*) code_alloc(sizeof(MyApp_Models_Guild));
{

#line 21 "./tests/samples/namespace.am"
        self->Tag = tag;
    }    return self;
}


#line 24 "./tests/samples/namespace.am"
code_string MyApp_Models_Guild_Describe(MyApp_Models_Guild* self) {

#line 25 "./tests/samples/namespace.am"
    return code_string_format("Guild [%s]", self->Tag);
}



#line 29 "./tests/samples/namespace.am"
/* class Program */
struct _MyApp_Models_Program {
};

MyApp_Models_Program* MyApp_Models_Program_new() {
    MyApp_Models_Program* self = (MyApp_Models_Program*) code_alloc(sizeof(MyApp_Models_Program));
    return self;
}


#line 30 "./tests/samples/namespace.am"
static void MyApp_Models_Program_Main(int argc, char** argv) {

#line 31 "./tests/samples/namespace.am"
    MyApp_Models_Player* p = MyApp_Models_Player_new("Arthus", 42);

#line 32 "./tests/samples/namespace.am"
    MyApp_Models_Guild* g = MyApp_Models_Guild_new("AMG");

#line 33 "./tests/samples/namespace.am"
    Console_WriteLine(MyApp_Models_Player_Info(p));

#line 34 "./tests/samples/namespace.am"
    Console_WriteLine(MyApp_Models_Guild_Describe(g));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    MyApp_Models_Program_Main(argc, argv);
    return 0;
}
