/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/null_safety.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static code_string Tests_Program_GetName(code_bool);
static i64 Tests_Program_Coalesce(i64, i64);
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/null_safety.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/null_safety.am"
static code_string Tests_Program_GetName(code_bool hasName) {

#line 5 "./tests/samples/null_safety.am"
    if (hasName) {

#line 6 "./tests/samples/null_safety.am"
        return "Arthus";
    }

#line 8 "./tests/samples/null_safety.am"
    return "Unknown";
}


#line 11 "./tests/samples/null_safety.am"
static i64 Tests_Program_Coalesce(i64 value, i64 fallback) {

#line 12 "./tests/samples/null_safety.am"
    if (value < 0) {

#line 13 "./tests/samples/null_safety.am"
        return fallback;
    }

#line 15 "./tests/samples/null_safety.am"
    return value;
}


#line 18 "./tests/samples/null_safety.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 19 "./tests/samples/null_safety.am"
    code_string name1 = Tests_Program_GetName(true);

#line 20 "./tests/samples/null_safety.am"
    code_string name2 = Tests_Program_GetName(false);

#line 21 "./tests/samples/null_safety.am"
    Console_WriteLine(code_string_format("name1: %s", name1));

#line 22 "./tests/samples/null_safety.am"
    Console_WriteLine(code_string_format("name2: %s", name2));

#line 24 "./tests/samples/null_safety.am"
    i64 v1 = Tests_Program_Coalesce(42, 0);

#line 25 "./tests/samples/null_safety.am"
    i64 v2 = Tests_Program_Coalesce(-1, 99);

#line 26 "./tests/samples/null_safety.am"
    Console_WriteLine(code_string_format("v1: %s", code_int_to_string(v1)));

#line 27 "./tests/samples/null_safety.am"
    Console_WriteLine(code_string_format("v2: %s", code_int_to_string(v2)));

#line 29 "./tests/samples/null_safety.am"
    code_bool flag1 = true;

#line 30 "./tests/samples/null_safety.am"
    code_bool flag2 = false;

#line 31 "./tests/samples/null_safety.am"
    code_bool both = flag1 && flag2;

#line 32 "./tests/samples/null_safety.am"
    code_bool either = flag1 || flag2;

#line 33 "./tests/samples/null_safety.am"
    Console_WriteLine(code_string_format("both: %s", ((both) ? "true" : "false")));

#line 34 "./tests/samples/null_safety.am"
    Console_WriteLine(code_string_format("either: %s", ((either) ? "true" : "false")));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
