/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/operators.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/operators.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/operators.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 5 "./tests/samples/operators.am"
    i64 a = 10;

#line 6 "./tests/samples/operators.am"
    i64 b = 3;

#line 8 "./tests/samples/operators.am"
    i64 add = a + b;

#line 9 "./tests/samples/operators.am"
    i64 sub = a - b;

#line 10 "./tests/samples/operators.am"
    i64 mul = a * b;

#line 11 "./tests/samples/operators.am"
    i64 div = a / b;

#line 12 "./tests/samples/operators.am"
    i64 mod = a % b;

#line 13 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("add: %s", code_int_to_string(add)));

#line 14 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("sub: %s", code_int_to_string(sub)));

#line 15 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("mul: %s", code_int_to_string(mul)));

#line 16 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("div: %s", code_int_to_string(div)));

#line 17 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("mod: %s", code_int_to_string(mod)));

#line 19 "./tests/samples/operators.am"
    code_bool eq = a == b;

#line 20 "./tests/samples/operators.am"
    code_bool ne = a != b;

#line 21 "./tests/samples/operators.am"
    code_bool gt = a > b;

#line 22 "./tests/samples/operators.am"
    code_bool gte = a >= 10;

#line 23 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("eq: %s", ((eq) ? "true" : "false")));

#line 24 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("ne: %s", ((ne) ? "true" : "false")));

#line 25 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("gt: %s", ((gt) ? "true" : "false")));

#line 26 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("gte: %s", ((gte) ? "true" : "false")));

#line 28 "./tests/samples/operators.am"
    code_bool and = true && false;

#line 29 "./tests/samples/operators.am"
    code_bool or = true || false;

#line 30 "./tests/samples/operators.am"
    void* not = !true;

#line 31 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("and: %s", ((and) ? "true" : "false")));

#line 32 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("or: %s", ((or) ? "true" : "false")));

#line 33 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("not: %s", code_int_to_string((i64)(intptr_t)(not))));

#line 35 "./tests/samples/operators.am"
    i64 x = 10;

#line 36 "./tests/samples/operators.am"
    x = x + 5;

#line 37 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("x: %s", code_int_to_string(x)));

#line 38 "./tests/samples/operators.am"
    x = x - 3;

#line 39 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("x: %s", code_int_to_string(x)));

#line 40 "./tests/samples/operators.am"
    x = x * 2;

#line 41 "./tests/samples/operators.am"
    Console_WriteLine(code_string_format("x: %s", code_int_to_string(x)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
