/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/pattern_advanced.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Classifier Tests_Classifier;
static code_string Tests_Classifier_Classify(i64);
static code_string Tests_Classifier_DayName(i64);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/pattern_advanced.am"
/* class Classifier */
struct _Tests_Classifier {
};

Tests_Classifier* Tests_Classifier_new() {
    Tests_Classifier* self = (Tests_Classifier*) code_alloc(sizeof(Tests_Classifier));
    return self;
}


#line 4 "./tests/samples/pattern_advanced.am"
static code_string Tests_Classifier_Classify(i64 n) {

#line 5 "./tests/samples/pattern_advanced.am"
    /* match */
    {
        int _match_idx = 0;
        if (n == 0) {
            return "zero";
        }
        else if (n == 1) {
            return "one";
        }
        else if (n >= 2 && n <= 9) {
            return "small";
        }
        else if (n >= 10 && n <= 99) {
            return "medium";
        }
        else if (n >= 100 && n <= 999) {
            return "large";
        }
        else {
            return "huge";
        }
    }

#line 13 "./tests/samples/pattern_advanced.am"
    return "unknown";
}


#line 16 "./tests/samples/pattern_advanced.am"
static code_string Tests_Classifier_DayName(i64 d) {

#line 17 "./tests/samples/pattern_advanced.am"
    /* match */
    {
        int _match_idx = 0;
        if (d == 1) {
            return "Monday";
        }
        else if (d == 2) {
            return "Tuesday";
        }
        else if (d == 3) {
            return "Wednesday";
        }
        else if (d == 4) {
            return "Thursday";
        }
        else if (d == 5) {
            return "Friday";
        }
        else if (d == 6) {
            return "Saturday";
        }
        else if (d == 7) {
            return "Sunday";
        }
        else {
            return "Invalid";
        }
    }

#line 27 "./tests/samples/pattern_advanced.am"
    return "Invalid";
}



#line 31 "./tests/samples/pattern_advanced.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 32 "./tests/samples/pattern_advanced.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 33 "./tests/samples/pattern_advanced.am"
    code_string c1 = Tests_Classifier_Classify(0);

#line 34 "./tests/samples/pattern_advanced.am"
    code_string c2 = Tests_Classifier_Classify(1);

#line 35 "./tests/samples/pattern_advanced.am"
    code_string c3 = Tests_Classifier_Classify(5);

#line 36 "./tests/samples/pattern_advanced.am"
    code_string c4 = Tests_Classifier_Classify(42);

#line 37 "./tests/samples/pattern_advanced.am"
    code_string c5 = Tests_Classifier_Classify(500);

#line 38 "./tests/samples/pattern_advanced.am"
    code_string c6 = Tests_Classifier_Classify(9999);

#line 39 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(c1);

#line 40 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(c2);

#line 41 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(c3);

#line 42 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(c4);

#line 43 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(c5);

#line 44 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(c6);

#line 46 "./tests/samples/pattern_advanced.am"
    code_string d1 = Tests_Classifier_DayName(1);

#line 47 "./tests/samples/pattern_advanced.am"
    code_string d5 = Tests_Classifier_DayName(5);

#line 48 "./tests/samples/pattern_advanced.am"
    code_string d7 = Tests_Classifier_DayName(7);

#line 49 "./tests/samples/pattern_advanced.am"
    code_string d8 = Tests_Classifier_DayName(8);

#line 50 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(d1);

#line 51 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(d5);

#line 52 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(d7);

#line 53 "./tests/samples/pattern_advanced.am"
    Console_WriteLine(d8);
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
