/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/record.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Point Tests_Point;
typedef struct _Tests_Color Tests_Color;
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/record.am"
/* record Point */
struct _Tests_Point {
    f32 X;
    f32 Y;
};

Tests_Point* Tests_Point_new(f32 X, f32 Y) {
    Tests_Point* self = (Tests_Point*) code_alloc(sizeof(Tests_Point));
    self->X = X;
    self->Y = Y;
    return self;
}



#line 5 "./tests/samples/record.am"
/* record Color */
struct _Tests_Color {
    i64 R;
    i64 G;
    i64 B;
};

Tests_Color* Tests_Color_new(i64 R, i64 G, i64 B) {
    Tests_Color* self = (Tests_Color*) code_alloc(sizeof(Tests_Color));
    self->R = R;
    self->G = G;
    self->B = B;
    return self;
}



#line 7 "./tests/samples/record.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 8 "./tests/samples/record.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 9 "./tests/samples/record.am"
    Tests_Point* p = Tests_Point_new(3.0, 4.0);

#line 10 "./tests/samples/record.am"
    Console_WriteLine(code_string_format("Point: (%s, %s)", code_float_to_string(p->X), code_float_to_string(p->Y)));

#line 12 "./tests/samples/record.am"
    Tests_Color* red = Tests_Color_new(255, 0, 0);

#line 13 "./tests/samples/record.am"
    Console_WriteLine(code_string_format("Color: (%s, %s, %s)", code_int_to_string(red->R), code_int_to_string(red->G), code_int_to_string(red->B)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
