/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/recursion.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Algo Tests_Algo;
static i64 Tests_Algo_Fib(i64);
static i64 Tests_Algo_SumDigits(i64);
static i64 Tests_Algo_Pow(i64, i64);
static i64 Tests_Algo_Gcd(i64, i64);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/recursion.am"
/* class Algo */
struct _Tests_Algo {
};

Tests_Algo* Tests_Algo_new() {
    Tests_Algo* self = (Tests_Algo*) code_alloc(sizeof(Tests_Algo));
    return self;
}


#line 4 "./tests/samples/recursion.am"
static i64 Tests_Algo_Fib(i64 n) {

#line 5 "./tests/samples/recursion.am"
    if (n <= 1) {
        return n;
    }

#line 6 "./tests/samples/recursion.am"
    return Tests_Algo_Fib(n - 1) + Tests_Algo_Fib(n - 2);
}


#line 9 "./tests/samples/recursion.am"
static i64 Tests_Algo_SumDigits(i64 n) {

#line 10 "./tests/samples/recursion.am"
    if (n < 10) {
        return n;
    }

#line 11 "./tests/samples/recursion.am"
    return n % 10 + Tests_Algo_SumDigits(n / 10);
}


#line 14 "./tests/samples/recursion.am"
static i64 Tests_Algo_Pow(i64 base, i64 exp) {

#line 15 "./tests/samples/recursion.am"
    if (exp == 0) {
        return 1;
    }

#line 16 "./tests/samples/recursion.am"
    return base * Tests_Algo_Pow(base, exp - 1);
}


#line 19 "./tests/samples/recursion.am"
static i64 Tests_Algo_Gcd(i64 a, i64 b) {

#line 20 "./tests/samples/recursion.am"
    if (b == 0) {
        return a;
    }

#line 21 "./tests/samples/recursion.am"
    return Tests_Algo_Gcd(b, a % b);
}



#line 25 "./tests/samples/recursion.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 26 "./tests/samples/recursion.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 27 "./tests/samples/recursion.am"
    i64 f0 = Tests_Algo_Fib(0);

#line 28 "./tests/samples/recursion.am"
    i64 f1 = Tests_Algo_Fib(1);

#line 29 "./tests/samples/recursion.am"
    i64 f7 = Tests_Algo_Fib(7);

#line 30 "./tests/samples/recursion.am"
    i64 f10 = Tests_Algo_Fib(10);

#line 31 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("fib(0) = %s", code_int_to_string(f0)));

#line 32 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("fib(1) = %s", code_int_to_string(f1)));

#line 33 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("fib(7) = %s", code_int_to_string(f7)));

#line 34 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("fib(10) = %s", code_int_to_string(f10)));

#line 36 "./tests/samples/recursion.am"
    i64 d1 = Tests_Algo_SumDigits(123);

#line 37 "./tests/samples/recursion.am"
    i64 d2 = Tests_Algo_SumDigits(999);

#line 38 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("digits(123) = %s", code_int_to_string(d1)));

#line 39 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("digits(999) = %s", code_int_to_string(d2)));

#line 41 "./tests/samples/recursion.am"
    i64 p1 = Tests_Algo_Pow(2, 8);

#line 42 "./tests/samples/recursion.am"
    i64 p2 = Tests_Algo_Pow(3, 4);

#line 43 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("pow(2,8) = %s", code_int_to_string(p1)));

#line 44 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("pow(3,4) = %s", code_int_to_string(p2)));

#line 46 "./tests/samples/recursion.am"
    i64 g1 = Tests_Algo_Gcd(48, 18);

#line 47 "./tests/samples/recursion.am"
    i64 g2 = Tests_Algo_Gcd(100, 75);

#line 48 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("gcd(48,18) = %s", code_int_to_string(g1)));

#line 49 "./tests/samples/recursion.am"
    Console_WriteLine(code_string_format("gcd(100,75) = %s", code_int_to_string(g2)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
