/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/static_class.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Counter Tests_Counter;
typedef struct _Tests_Calculator Tests_Calculator;
static i64 Tests_Calculator_Add(i64, i64);
static i64 Tests_Calculator_Sub(i64, i64);
static i64 Tests_Calculator_Mul(i64, i64);
static code_bool Tests_Calculator_IsEven(i64);
static i64 Tests_Calculator_Abs(i64);
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/static_class.am"
/* class Counter */
struct _Tests_Counter {
    i64 Value;
};


#line 6 "./tests/samples/static_class.am"
Tests_Counter* Tests_Counter_new() {
    Tests_Counter* self = (Tests_Counter*) code_alloc(sizeof(Tests_Counter));
{

#line 7 "./tests/samples/static_class.am"
        self->Value = 0;
    }    return self;
}


#line 10 "./tests/samples/static_class.am"
void Tests_Counter_Inc(Tests_Counter* self) {

#line 11 "./tests/samples/static_class.am"
    self->Value = self->Value + 1;
}


#line 14 "./tests/samples/static_class.am"
void Tests_Counter_Dec(Tests_Counter* self) {

#line 15 "./tests/samples/static_class.am"
    self->Value = self->Value - 1;
}


#line 18 "./tests/samples/static_class.am"
void Tests_Counter_Reset(Tests_Counter* self) {

#line 19 "./tests/samples/static_class.am"
    self->Value = 0;
}


#line 22 "./tests/samples/static_class.am"
code_bool Tests_Counter_IsZero(Tests_Counter* self) {

#line 23 "./tests/samples/static_class.am"
    return self->Value == 0;
}



#line 27 "./tests/samples/static_class.am"
/* class Calculator */
struct _Tests_Calculator {
};

Tests_Calculator* Tests_Calculator_new() {
    Tests_Calculator* self = (Tests_Calculator*) code_alloc(sizeof(Tests_Calculator));
    return self;
}


#line 28 "./tests/samples/static_class.am"
static i64 Tests_Calculator_Add(i64 a, i64 b) {
    return a + b;
}


#line 29 "./tests/samples/static_class.am"
static i64 Tests_Calculator_Sub(i64 a, i64 b) {
    return a - b;
}


#line 30 "./tests/samples/static_class.am"
static i64 Tests_Calculator_Mul(i64 a, i64 b) {
    return a * b;
}


#line 31 "./tests/samples/static_class.am"
static code_bool Tests_Calculator_IsEven(i64 n) {
    return n % 2 == 0;
}


#line 32 "./tests/samples/static_class.am"
static i64 Tests_Calculator_Abs(i64 n) {

#line 33 "./tests/samples/static_class.am"
    if (n < 0) {
        return 0 - n;
    }

#line 34 "./tests/samples/static_class.am"
    return n;
}



#line 38 "./tests/samples/static_class.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 39 "./tests/samples/static_class.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 40 "./tests/samples/static_class.am"
    Tests_Counter* c = Tests_Counter_new();

#line 41 "./tests/samples/static_class.am"
    code_bool z1 = Tests_Counter_IsZero(c);

#line 42 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("zero: %s", ((z1) ? "true" : "false")));

#line 43 "./tests/samples/static_class.am"
    Tests_Counter_Inc(c);

#line 44 "./tests/samples/static_class.am"
    Tests_Counter_Inc(c);

#line 45 "./tests/samples/static_class.am"
    Tests_Counter_Inc(c);

#line 46 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("val: %s", code_int_to_string(c->Value)));

#line 47 "./tests/samples/static_class.am"
    Tests_Counter_Dec(c);

#line 48 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("val: %s", code_int_to_string(c->Value)));

#line 49 "./tests/samples/static_class.am"
    Tests_Counter_Reset(c);

#line 50 "./tests/samples/static_class.am"
    code_bool z2 = Tests_Counter_IsZero(c);

#line 51 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("zero: %s", ((z2) ? "true" : "false")));

#line 53 "./tests/samples/static_class.am"
    i64 sum = Tests_Calculator_Add(15, 27);

#line 54 "./tests/samples/static_class.am"
    i64 diff = Tests_Calculator_Sub(50, 8);

#line 55 "./tests/samples/static_class.am"
    i64 prod = Tests_Calculator_Mul(6, 7);

#line 56 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("sum: %s", code_int_to_string(sum)));

#line 57 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("diff: %s", code_int_to_string(diff)));

#line 58 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("prod: %s", code_int_to_string(prod)));

#line 60 "./tests/samples/static_class.am"
    code_bool even = Tests_Calculator_IsEven(42);

#line 61 "./tests/samples/static_class.am"
    i64 abs = Tests_Calculator_Abs(-17);

#line 62 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("even: %s", ((even) ? "true" : "false")));

#line 63 "./tests/samples/static_class.am"
    Console_WriteLine(code_string_format("abs: %s", code_int_to_string(abs)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
