/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/stdlib_string.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */
#include "Amalgame_String.h"

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 5 "./tests/samples/stdlib_string.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 6 "./tests/samples/stdlib_string.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 8 "./tests/samples/stdlib_string.am"
    void* len = String_Length("Hello");

#line 9 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("len = %s", len));

#line 12 "./tests/samples/stdlib_string.am"
    void* has = String_Contains("Hello World", "World");

#line 13 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("contains = %s", has));

#line 15 "./tests/samples/stdlib_string.am"
    void* sw = String_StartsWith("Hello", "He");

#line 16 "./tests/samples/stdlib_string.am"
    void* ew = String_EndsWith("Hello", "lo");

#line 17 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("startsWith = %s", sw));

#line 18 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("endsWith = %s", ew));

#line 20 "./tests/samples/stdlib_string.am"
    void* idx = String_IndexOf("Hello World", "World");

#line 21 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("indexOf = %s", idx));

#line 24 "./tests/samples/stdlib_string.am"
    void* up = String_ToUpper("hello");

#line 25 "./tests/samples/stdlib_string.am"
    void* lo = String_ToLower("WORLD");

#line 26 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("upper = %s", up));

#line 27 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("lower = %s", lo));

#line 30 "./tests/samples/stdlib_string.am"
    void* trimmed = String_Trim("  hello  ");

#line 31 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("trim = '%s'", trimmed));

#line 34 "./tests/samples/stdlib_string.am"
    void* replaced = String_Replace("Hello World", "World", "Amalgame");

#line 35 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("replace = %s", replaced));

#line 38 "./tests/samples/stdlib_string.am"
    void* rep = String_Repeat("ab", 3);

#line 39 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("repeat = %s", rep));

#line 42 "./tests/samples/stdlib_string.am"
    void* n = String_ToInt("42");

#line 43 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("toInt = %s", n));

#line 45 "./tests/samples/stdlib_string.am"
    void* s = String_FromInt(123);

#line 46 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("fromInt = %s", s));

#line 48 "./tests/samples/stdlib_string.am"
    void* empty = String_IsEmpty("");

#line 49 "./tests/samples/stdlib_string.am"
    Console_WriteLine(code_string_format("isEmpty = %s", empty));

#line 51 "./tests/samples/stdlib_string.am"
    Console_WriteLine("String test done");
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
