/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/stdlib_net.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */
#include "Amalgame_Net.h"

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 5 "./tests/samples/stdlib_net.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 6 "./tests/samples/stdlib_net.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 7 "./tests/samples/stdlib_net.am"
    AmalgameHttpResponse* resp = Http_Get("https://httpbin.org/get");

#line 8 "./tests/samples/stdlib_net.am"
    i64 status = resp->Status;

#line 9 "./tests/samples/stdlib_net.am"
    code_bool ok = resp->Ok;

#line 10 "./tests/samples/stdlib_net.am"
    Console_WriteLine(code_string_format("status: %s", code_int_to_string(status)));

#line 11 "./tests/samples/stdlib_net.am"
    Console_WriteLine(code_string_format("ok: %s", ((ok) ? "true" : "false")));

#line 13 "./tests/samples/stdlib_net.am"
    AmalgameHttpResponse* resp2 = Http_Get("https://httpbin.org/get");

#line 14 "./tests/samples/stdlib_net.am"
    code_bool ok2 = resp2->Ok;

#line 15 "./tests/samples/stdlib_net.am"
    Console_WriteLine(code_string_format("headers ok: %s", ((ok2) ? "true" : "false")));

#line 17 "./tests/samples/stdlib_net.am"
    code_string jsonBody = "name=Arthus";

#line 18 "./tests/samples/stdlib_net.am"
    AmalgameHttpResponse* resp3 = Http_Post("https://httpbin.org/post", jsonBody);

#line 19 "./tests/samples/stdlib_net.am"
    code_bool ok3 = resp3->Ok;

#line 20 "./tests/samples/stdlib_net.am"
    Console_WriteLine(code_string_format("post ok: %s", ((ok3) ? "true" : "false")));

#line 22 "./tests/samples/stdlib_net.am"
    AmalgameHttpResponse* resp4 = Http_PostJson("https://httpbin.org/post", jsonBody);

#line 23 "./tests/samples/stdlib_net.am"
    code_bool ok4 = resp4->Ok;

#line 24 "./tests/samples/stdlib_net.am"
    Console_WriteLine(code_string_format("postJson ok: %s", ((ok4) ? "true" : "false")));

#line 26 "./tests/samples/stdlib_net.am"
    Console_WriteLine("Net test done");
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
