/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/stdlib_math.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */
#include "Amalgame_Math.h"

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 5 "./tests/samples/stdlib_math.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 6 "./tests/samples/stdlib_math.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 7 "./tests/samples/stdlib_math.am"
    f64 sq = Math_Sqrt(16.0);

#line 8 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("sqrt(16) = %s", code_float_to_string(sq)));

#line 10 "./tests/samples/stdlib_math.am"
    i64 pw = Math_PowI(2, 10);

#line 11 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("pow(2,10) = %s", code_int_to_string(pw)));

#line 13 "./tests/samples/stdlib_math.am"
    i64 ab = Math_AbsI(-42);

#line 14 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("abs(-42) = %s", code_int_to_string(ab)));

#line 16 "./tests/samples/stdlib_math.am"
    i64 mx = Math_MaxI(10, 42);

#line 17 "./tests/samples/stdlib_math.am"
    i64 mn = Math_MinI(10, 42);

#line 18 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("max = %s", code_int_to_string(mx)));

#line 19 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("min = %s", code_int_to_string(mn)));

#line 21 "./tests/samples/stdlib_math.am"
    i64 cl = Math_ClampI(150, 0, 100);

#line 22 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("clamp = %s", code_int_to_string(cl)));

#line 24 "./tests/samples/stdlib_math.am"
    i64 gcd = Math_Gcd(48, 18);

#line 25 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("gcd(48,18) = %s", code_int_to_string(gcd)));

#line 27 "./tests/samples/stdlib_math.am"
    code_bool p1 = Math_IsPrime(17);

#line 28 "./tests/samples/stdlib_math.am"
    code_bool p2 = Math_IsPrime(18);

#line 29 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("prime(17) = %s", ((p1) ? "true" : "false")));

#line 30 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("prime(18) = %s", ((p2) ? "true" : "false")));

#line 32 "./tests/samples/stdlib_math.am"
    Math_SeedRandom(42);

#line 33 "./tests/samples/stdlib_math.am"
    Console_WriteLine("rand seeded: ok");

#line 35 "./tests/samples/stdlib_math.am"
    code_bool fin = Math_IsFinite(1.0);

#line 36 "./tests/samples/stdlib_math.am"
    Console_WriteLine(code_string_format("finite = %s", ((fin) ? "true" : "false")));

#line 38 "./tests/samples/stdlib_math.am"
    Console_WriteLine("Math test done");
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
