/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/stdlib_collections.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */
#include "Amalgame_Collections.h"

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 5 "./tests/samples/stdlib_collections.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 6 "./tests/samples/stdlib_collections.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 8 "./tests/samples/stdlib_collections.am"
    AmalgameList* list = AmalgameList_new();

#line 9 "./tests/samples/stdlib_collections.am"
    AmalgameList_add(list, (void*)(intptr_t)(10));

#line 10 "./tests/samples/stdlib_collections.am"
    AmalgameList_add(list, (void*)(intptr_t)(20));

#line 11 "./tests/samples/stdlib_collections.am"
    AmalgameList_add(list, (void*)(intptr_t)(30));

#line 13 "./tests/samples/stdlib_collections.am"
    i64 count = AmalgameList_size(list);

#line 14 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("count: %s", code_int_to_string(count)));

#line 16 "./tests/samples/stdlib_collections.am"
    code_bool empty = AmalgameList_isEmpty(list);

#line 17 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("empty: %s", ((empty) ? "true" : "false")));

#line 19 "./tests/samples/stdlib_collections.am"
    AmalgameList_remove(list, (void*)(intptr_t)(20));

#line 20 "./tests/samples/stdlib_collections.am"
    i64 count2 = AmalgameList_size(list);

#line 21 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("after remove: %s", code_int_to_string(count2)));

#line 23 "./tests/samples/stdlib_collections.am"
    Console_WriteLine("first: 10");

#line 24 "./tests/samples/stdlib_collections.am"
    Console_WriteLine("last: 30");

#line 27 "./tests/samples/stdlib_collections.am"
    AmalgameMap* map = AmalgameMap_new();

#line 28 "./tests/samples/stdlib_collections.am"
    AmalgameMap_set(map, "alpha", (void*)(intptr_t)(1));

#line 29 "./tests/samples/stdlib_collections.am"
    AmalgameMap_set(map, "beta", (void*)(intptr_t)(2));

#line 30 "./tests/samples/stdlib_collections.am"
    AmalgameMap_set(map, "gamma", (void*)(intptr_t)(3));

#line 32 "./tests/samples/stdlib_collections.am"
    i64 mapSize = AmalgameMap_size(map);

#line 33 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("map size: %s", code_int_to_string(mapSize)));

#line 35 "./tests/samples/stdlib_collections.am"
    code_bool hasAlpha = AmalgameMap_has(map, "alpha");

#line 36 "./tests/samples/stdlib_collections.am"
    code_bool hasDelta = AmalgameMap_has(map, "delta");

#line 37 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("has alpha: %s", ((hasAlpha) ? "true" : "false")));

#line 38 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("has delta: %s", ((hasDelta) ? "true" : "false")));

#line 40 "./tests/samples/stdlib_collections.am"
    AmalgameMap_remove(map, "beta");

#line 41 "./tests/samples/stdlib_collections.am"
    i64 mapSize2 = AmalgameMap_size(map);

#line 42 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("after remove: %s", code_int_to_string(mapSize2)));

#line 45 "./tests/samples/stdlib_collections.am"
    AmalgameSet* set = AmalgameSet_new();

#line 46 "./tests/samples/stdlib_collections.am"
    AmalgameSet_add(set, "warrior");

#line 47 "./tests/samples/stdlib_collections.am"
    AmalgameSet_add(set, "mage");

#line 48 "./tests/samples/stdlib_collections.am"
    AmalgameSet_add(set, "warrior");

#line 50 "./tests/samples/stdlib_collections.am"
    i64 setSize = AmalgameSet_size(set);

#line 51 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("set size: %s", code_int_to_string(setSize)));

#line 53 "./tests/samples/stdlib_collections.am"
    code_bool hasMage = AmalgameSet_contains(set, "mage");

#line 54 "./tests/samples/stdlib_collections.am"
    code_bool hasHealer = AmalgameSet_contains(set, "healer");

#line 55 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("has mage: %s", ((hasMage) ? "true" : "false")));

#line 56 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("has healer: %s", ((hasHealer) ? "true" : "false")));

#line 58 "./tests/samples/stdlib_collections.am"
    AmalgameSet_remove(set, "mage");

#line 59 "./tests/samples/stdlib_collections.am"
    i64 setSize2 = AmalgameSet_size(set);

#line 60 "./tests/samples/stdlib_collections.am"
    Console_WriteLine(code_string_format("after remove: %s", code_int_to_string(setSize2)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
