/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/stdlib_io.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */
#include "Amalgame_IO.h"

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 5 "./tests/samples/stdlib_io.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 6 "./tests/samples/stdlib_io.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 7 "./tests/samples/stdlib_io.am"
    Console_WriteLine("IO test start");

#line 9 "./tests/samples/stdlib_io.am"
    void* ok = File_WriteAll("/tmp/amalgame_test.txt", "Hello from Amalgame!");

#line 10 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("write ok: %s", ok));

#line 12 "./tests/samples/stdlib_io.am"
    void* exists = File_Exists("/tmp/amalgame_test.txt");

#line 13 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("exists: %s", exists));

#line 15 "./tests/samples/stdlib_io.am"
    void* content = File_ReadAll("/tmp/amalgame_test.txt");

#line 16 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("content: %s", content));

#line 18 "./tests/samples/stdlib_io.am"
    void* size = File_Size("/tmp/amalgame_test.txt");

#line 19 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("size: %s", size));

#line 21 "./tests/samples/stdlib_io.am"
    void* combined = Path_Combine("/tmp", "test.txt");

#line 22 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("path: %s", combined));

#line 24 "./tests/samples/stdlib_io.am"
    void* ext = Path_GetExtension("hello.am");

#line 25 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("ext: %s", ext));

#line 27 "./tests/samples/stdlib_io.am"
    void* fname = Path_GetFilename("/home/user/hello.am");

#line 28 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("file: %s", fname));

#line 30 "./tests/samples/stdlib_io.am"
    void* deleted = File_Delete("/tmp/amalgame_test.txt");

#line 31 "./tests/samples/stdlib_io.am"
    Console_WriteLine(code_string_format("deleted: %s", deleted));

#line 33 "./tests/samples/stdlib_io.am"
    Console_WriteLine("IO test done");
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
