/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/strings.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/strings.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/strings.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 5 "./tests/samples/strings.am"
    code_string hello = "Hello";

#line 6 "./tests/samples/strings.am"
    code_string world = "World";

#line 7 "./tests/samples/strings.am"
    code_string greet = code_string_concat(code_string_concat(code_string_concat(hello, ", "), world), "!");

#line 8 "./tests/samples/strings.am"
    Console_WriteLine(greet);

#line 10 "./tests/samples/strings.am"
    i64 x = 6;

#line 11 "./tests/samples/strings.am"
    i64 y = 7;

#line 12 "./tests/samples/strings.am"
    i64 product = x * y;

#line 13 "./tests/samples/strings.am"
    Console_WriteLine(code_string_format("Product: %s", code_int_to_string(product)));

#line 15 "./tests/samples/strings.am"
    code_string name = "Amalgame";

#line 16 "./tests/samples/strings.am"
    if (name == "Amalgame") {

#line 17 "./tests/samples/strings.am"
        Console_WriteLine("Name matches!");
    }

#line 20 "./tests/samples/strings.am"
    code_string sentence = "The quick brown fox";

#line 21 "./tests/samples/strings.am"
    Console_WriteLine(sentence);

#line 23 "./tests/samples/strings.am"
    i64 n = 5;

#line 24 "./tests/samples/strings.am"
    i64 doubled = n * 2;

#line 25 "./tests/samples/strings.am"
    Console_WriteLine(code_string_format("Doubled: %s", code_int_to_string(doubled)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
