/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/try_catch.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_DivisionError Tests_DivisionError;
typedef struct _Tests_Program Tests_Program;
static i64 Tests_Program_SafeDiv(i64, i64);
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/try_catch.am"
/* class DivisionError */
struct _Tests_DivisionError {
    code_string Message;
};


#line 6 "./tests/samples/try_catch.am"
Tests_DivisionError* Tests_DivisionError_new(code_string msg) {
    Tests_DivisionError* self = (Tests_DivisionError*) code_alloc(sizeof(Tests_DivisionError));
{

#line 7 "./tests/samples/try_catch.am"
        self->Message = msg;
    }    return self;
}



#line 11 "./tests/samples/try_catch.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 12 "./tests/samples/try_catch.am"
static i64 Tests_Program_SafeDiv(i64 a, i64 b) {

#line 13 "./tests/samples/try_catch.am"
    if (b == 0) {

#line 14 "./tests/samples/try_catch.am"
        _am_throw((void*)(Tests_DivisionError_new("division by zero")), "DivisionError", "division by zero");
    }

#line 16 "./tests/samples/try_catch.am"
    return a / b;
}


#line 19 "./tests/samples/try_catch.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 21 "./tests/samples/try_catch.am"
        {
        jmp_buf _am_prev_env;
        memcpy(&_am_prev_env, &_am_ex.env, sizeof(jmp_buf));
        int _am_caught = setjmp(_am_ex.env);
        if (_am_caught == 0) {
            i64 result = Tests_Program_SafeDiv(10, 2);;
            Console_WriteLine(code_string_format("result: %s", code_int_to_string(result)));
            _am_ex.active = 0;
        } else {
            void* e = _am_ex.value;
            _am_ex.active = 0;
            Console_WriteLine("error caught");
        }
        memcpy(&_am_ex.env, &_am_prev_env, sizeof(jmp_buf));
    }

#line 29 "./tests/samples/try_catch.am"
        {
        jmp_buf _am_prev_env;
        memcpy(&_am_prev_env, &_am_ex.env, sizeof(jmp_buf));
        int _am_caught = setjmp(_am_ex.env);
        if (_am_caught == 0) {
            i64 result = Tests_Program_SafeDiv(10, 0);;
            Console_WriteLine("should not reach");
            _am_ex.active = 0;
        } else {
            void* e = _am_ex.value;
            _am_ex.active = 0;
            Console_WriteLine("caught: division by zero");
        }
        memcpy(&_am_ex.env, &_am_prev_env, sizeof(jmp_buf));
    }

#line 37 "./tests/samples/try_catch.am"
        {
        jmp_buf _am_prev_env;
        memcpy(&_am_prev_env, &_am_ex.env, sizeof(jmp_buf));
        int _am_caught = setjmp(_am_ex.env);
        if (_am_caught == 0) {
            i64 x = 42;;
            Console_WriteLine(code_string_format("try ok: %s", code_int_to_string(x)));
            _am_ex.active = 0;
        } else {
            void* e = _am_ex.value;
            _am_ex.active = 0;
            Console_WriteLine("catch");
        }
        memcpy(&_am_ex.env, &_am_prev_env, sizeof(jmp_buf));
        /* finally */
        Console_WriteLine("finally runs");
    }

#line 46 "./tests/samples/try_catch.am"
    Console_WriteLine("done");
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
