/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.6.0
 * Source    : ./tests/samples/tuples.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

typedef struct { i64 _0; code_string _1; } _Tuple_i64_str;
typedef struct { i64 _0; i64 _1; code_bool _2; } _Tuple_i64_i64_bool;
/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static _Tuple_i64_str Tests_Program_GetPlayer(void);
static _Tuple_i64_i64_bool Tests_Program_Divide(i64, i64);
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/tuples.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 5 "./tests/samples/tuples.am"
static _Tuple_i64_str Tests_Program_GetPlayer() {

#line 6 "./tests/samples/tuples.am"
    return (_Tuple_i64_str){42, "Arthus"};
}


#line 10 "./tests/samples/tuples.am"
static _Tuple_i64_i64_bool Tests_Program_Divide(i64 a, i64 b) {

#line 11 "./tests/samples/tuples.am"
    if (b == 0) {

#line 12 "./tests/samples/tuples.am"
        return (_Tuple_i64_i64_bool){0, 0, false};
    }

#line 14 "./tests/samples/tuples.am"
    return (_Tuple_i64_i64_bool){a / b, a % b, true};
}


#line 17 "./tests/samples/tuples.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 19 "./tests/samples/tuples.am"
        _Tuple_i64_str _am_tuple_0 = Tests_Program_GetPlayer();
    i64 level = _am_tuple_0._0;
    code_string name = _am_tuple_0._1;


#line 20 "./tests/samples/tuples.am"
    Console_WriteLine(code_string_format("name: %s", name));

#line 21 "./tests/samples/tuples.am"
    Console_WriteLine(code_string_format("level: %s", code_int_to_string(level)));

#line 24 "./tests/samples/tuples.am"
        _Tuple_i64_i64_bool _am_tuple_1 = Tests_Program_Divide(17, 5);
    i64 q = _am_tuple_1._0;
    i64 r = _am_tuple_1._1;
    code_bool ok = _am_tuple_1._2;


#line 25 "./tests/samples/tuples.am"
    Console_WriteLine(code_string_format("ok: %s", ((ok) ? "true" : "false")));

#line 26 "./tests/samples/tuples.am"
    Console_WriteLine(code_string_format("quotient: %s", code_int_to_string(q)));

#line 27 "./tests/samples/tuples.am"
    Console_WriteLine(code_string_format("remainder: %s", code_int_to_string(r)));

#line 30 "./tests/samples/tuples.am"
        _Tuple_i64_i64_bool _am_tuple_2 = Tests_Program_Divide(10, 0);
    i64 q2 = _am_tuple_2._0;
    i64 r2 = _am_tuple_2._1;
    code_bool ok2 = _am_tuple_2._2;


#line 31 "./tests/samples/tuples.am"
    Console_WriteLine(code_string_format("div ok: %s", ((ok2) ? "true" : "false")));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
