/* ═══════════════════════════════════════
 * Generated by Amalgame Transpiler v0.3.0
 * Source    : ./tests/samples/type_explicit.am
 * Mode      : Executable
 * Namespace : Tests
 * DO NOT EDIT MANUALLY
 * ═══════════════════════════════════════
 */

#include "_runtime.h"

/* namespace Tests */

/* ── Forward Declarations ── */
typedef struct _Tests_Program Tests_Program;
static void Tests_Program_Main(int, char**);



#line 3 "./tests/samples/type_explicit.am"
/* class Program */
struct _Tests_Program {
};

Tests_Program* Tests_Program_new() {
    Tests_Program* self = (Tests_Program*) code_alloc(sizeof(Tests_Program));
    return self;
}


#line 4 "./tests/samples/type_explicit.am"
static void Tests_Program_Main(int argc, char** argv) {

#line 5 "./tests/samples/type_explicit.am"
    i64 x = 42;

#line 6 "./tests/samples/type_explicit.am"
    f32 y = 3.14;

#line 7 "./tests/samples/type_explicit.am"
    code_string s = "typed";

#line 8 "./tests/samples/type_explicit.am"
    code_bool b = true;

#line 10 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("x: %s", code_int_to_string(x)));

#line 11 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("s: %s", s));

#line 12 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("b: %s", ((b) ? "true" : "false")));

#line 14 "./tests/samples/type_explicit.am"
    i64 count = 0;

#line 15 "./tests/samples/type_explicit.am"
    count = count + 1;

#line 16 "./tests/samples/type_explicit.am"
    count = count + 1;

#line 17 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("count: %s", code_int_to_string(count)));

#line 19 "./tests/samples/type_explicit.am"
    i64 big = 1000000;

#line 20 "./tests/samples/type_explicit.am"
    i64 result = big * 42;

#line 21 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("big: %s", code_int_to_string(result)));

#line 23 "./tests/samples/type_explicit.am"
    f32 pi = 3.14159;

#line 24 "./tests/samples/type_explicit.am"
    f32 r = 2.0;

#line 25 "./tests/samples/type_explicit.am"
    f32 area = pi * r * r;

#line 26 "./tests/samples/type_explicit.am"
    code_bool pos = area > 0.0;

#line 27 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("area positive: %s", ((pos) ? "true" : "false")));

#line 29 "./tests/samples/type_explicit.am"
    i64 neg = 0 - 42;

#line 30 "./tests/samples/type_explicit.am"
    i64 abs = 0 - neg;

#line 31 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("neg: %s", code_int_to_string(neg)));

#line 32 "./tests/samples/type_explicit.am"
    Console_WriteLine(code_string_format("abs: %s", code_int_to_string(abs)));
}



/* ── Entry point ── */
int main(int argc, char** argv) {
    code_runtime_init();
    Tests_Program_Main(argc, argv);
    return 0;
}
