#pragma once
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdarg.h>
#define ESP_WIFI_OS_ADAPTER_VERSION  0x00000008
#define ESP_WIFI_OS_ADAPTER_MAGIC    0xDEADBEAF
/* esp32s3 layout: esp32-only and C6/C5/C61 blocks omitted; _slowclk_cal_get kept */
typedef struct wifi_osi_funcs_t {
    int32_t _version;
    bool (* _env_is_chip)(void);
    void (*_set_intr)(int32_t,uint32_t,uint32_t,int32_t);
    void (*_clear_intr)(uint32_t,uint32_t);
    void (*_set_isr)(int32_t,void*,void*);
    void (*_ints_on)(uint32_t);
    void (*_ints_off)(uint32_t);
    bool (* _is_from_isr)(void);
    void *(* _spin_lock_create)(void);
    void (* _spin_lock_delete)(void*);
    uint32_t (*_wifi_int_disable)(void*);
    void (*_wifi_int_restore)(void*,uint32_t);
    void (*_task_yield_from_isr)(void);
    void *(*_semphr_create)(uint32_t,uint32_t);
    void (*_semphr_delete)(void*);
    int32_t (*_semphr_take)(void*,uint32_t);
    int32_t (*_semphr_give)(void*);
    void *(*_wifi_thread_semphr_get)(void);
    void *(*_mutex_create)(void);
    void *(*_recursive_mutex_create)(void);
    void (*_mutex_delete)(void*);
    int32_t (*_mutex_lock)(void*);
    int32_t (*_mutex_unlock)(void*);
    void *(* _queue_create)(uint32_t,uint32_t);
    void (* _queue_delete)(void*);
    int32_t (* _queue_send)(void*,void*,uint32_t);
    int32_t (* _queue_send_from_isr)(void*,void*,void*);
    int32_t (* _queue_send_to_back)(void*,void*,uint32_t);
    int32_t (* _queue_send_to_front)(void*,void*,uint32_t);
    int32_t (* _queue_recv)(void*,void*,uint32_t);
    uint32_t (* _queue_msg_waiting)(void*);
    void *(* _event_group_create)(void);
    void (* _event_group_delete)(void*);
    uint32_t (* _event_group_set_bits)(void*,uint32_t);
    uint32_t (* _event_group_clear_bits)(void*,uint32_t);
    uint32_t (* _event_group_wait_bits)(void*,uint32_t,int,int,uint32_t);
    int32_t (* _task_create_pinned_to_core)(void*,const char*,uint32_t,void*,uint32_t,void*,uint32_t);
    int32_t (* _task_create)(void*,const char*,uint32_t,void*,uint32_t,void*);
    void (* _task_delete)(void*);
    void (* _task_delay)(uint32_t);
    int32_t (* _task_ms_to_tick)(uint32_t);
    void *(* _task_get_current_task)(void);
    int32_t (* _task_get_max_priority)(void);
    void *(* _malloc)(size_t);
    void (* _free)(void*);
    int32_t (* _event_post)(const char*,int32_t,void*,size_t,uint32_t);
    uint32_t (* _get_free_heap_size)(void);
    uint32_t (* _rand)(void);
    void (* _dport_access_stall_other_cpu_start_wrap)(void);
    void (* _dport_access_stall_other_cpu_end_wrap)(void);
    void (* _wifi_apb80m_request)(void);
    void (* _wifi_apb80m_release)(void);
    void (* _phy_disable)(void);
    void (* _phy_enable)(void);
    int (* _phy_update_country_info)(const char*);
    int (* _read_mac)(uint8_t*,unsigned int);
    void (* _timer_arm)(void*,uint32_t,bool);
    void (* _timer_disarm)(void*);
    void (* _timer_done)(void*);
    void (* _timer_setfn)(void*,void*,void*);
    void (* _timer_arm_us)(void*,uint32_t,bool);
    void (* _wifi_reset_mac)(void);
    void (* _wifi_clock_enable)(void);
    void (* _wifi_clock_disable)(void);
    void (* _wifi_rtc_enable_iso)(void);
    void (* _wifi_rtc_disable_iso)(void);
    int64_t (* _esp_timer_get_time)(void);
    int (* _nvs_set_i8)(uint32_t,const char*,int8_t);
    int (* _nvs_get_i8)(uint32_t,const char*,int8_t*);
    int (* _nvs_set_u8)(uint32_t,const char*,uint8_t);
    int (* _nvs_get_u8)(uint32_t,const char*,uint8_t*);
    int (* _nvs_set_u16)(uint32_t,const char*,uint16_t);
    int (* _nvs_get_u16)(uint32_t,const char*,uint16_t*);
    int (* _nvs_open)(const char*,unsigned int,uint32_t*);
    void (* _nvs_close)(uint32_t);
    int (* _nvs_commit)(uint32_t);
    int (* _nvs_set_blob)(uint32_t,const char*,const void*,size_t);
    int (* _nvs_get_blob)(uint32_t,const char*,void*,size_t*);
    int (* _nvs_erase_key)(uint32_t,const char*);
    int (* _get_random)(uint8_t*,size_t);
    int (* _get_time)(void*);
    unsigned long (* _random)(void);
    uint32_t (* _slowclk_cal_get)(void);
    void (* _log_write)(unsigned int,const char*,const char*,...);
    void (* _log_writev)(unsigned int,const char*,const char*,va_list);
    uint32_t (* _log_timestamp)(void);
    void * (* _malloc_internal)(size_t);
    void * (* _realloc_internal)(void*,size_t);
    void * (* _calloc_internal)(size_t,size_t);
    void * (* _zalloc_internal)(size_t);
    void * (* _wifi_malloc)(size_t);
    void * (* _wifi_realloc)(void*,size_t);
    void * (* _wifi_calloc)(size_t,size_t);
    void * (* _wifi_zalloc)(size_t);
    void * (* _wifi_create_queue)(int,int);
    void (* _wifi_delete_queue)(void*);
    int (* _coex_init)(void);
    void (* _coex_deinit)(void);
    int (* _coex_enable)(void);
    void (* _coex_disable)(void);
    uint32_t (* _coex_status_get)(void);
    void (* _coex_condition_set)(uint32_t,bool);
    int (* _coex_wifi_request)(uint32_t,uint32_t,uint32_t);
    int (* _coex_wifi_release)(uint32_t);
    int (* _coex_wifi_channel_set)(uint8_t,uint8_t);
    int (* _coex_event_duration_get)(uint32_t,uint32_t*);
    int (* _coex_pti_get)(uint32_t,uint8_t*);
    void (* _coex_schm_status_bit_clear)(uint32_t,uint32_t);
    void (* _coex_schm_status_bit_set)(uint32_t,uint32_t);
    int (* _coex_schm_interval_set)(uint32_t);
    uint32_t (* _coex_schm_interval_get)(void);
    uint8_t (* _coex_schm_curr_period_get)(void);
    void * (* _coex_schm_curr_phase_get)(void);
    int (* _coex_schm_process_restart)(void);
    int (* _coex_schm_register_cb)(int,int(*)(int));
    int (* _coex_register_start_cb)(int(*)(void));
    int (*_coex_schm_flexible_period_set)(uint8_t);
    uint8_t (*_coex_schm_flexible_period_get)(void);
    void * (*_coex_schm_get_phase_by_idx)(int);
    int32_t _magic;
} wifi_osi_funcs_t;
